# Generated by Django 4.0.4 on 2023-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.FloatField(default=1700825328.312177),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='created_time',
            field=models.FloatField(default=1700825328.311836),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_time',
            field=models.FloatField(default=1700825328.312017),
        ),
    ]
