# Generated by Django 4.1.3 on 2023-12-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_userprofile_profile_json_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.FloatField(default=1703173296.095456),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='created_time',
            field=models.FloatField(default=1703173296.094445),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_time',
            field=models.FloatField(default=1703173296.094445),
        ),
    ]
