# Generated by Django 4.1.3 on 2023-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_time', models.FloatField(default=1703151045.390725)),
                ('polish_text', models.TextField(default='')),
                ('is_summary', models.BooleanField(default=False)),
                ('is_send', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AudioSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FullAudio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checkCode', models.CharField(max_length=64)),
                ('full_text', models.TextField()),
                ('summary', models.JSONField(default=dict)),
                ('updated_time', models.FloatField(default=1703151045.391723)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instruction', models.TextField(default='default instruction')),
                ('meeting_name', models.TextField(default='')),
            ],
        ),
    ]
